baseURL = 'https://jeffeehsiung.github.io/signal-blog/'
locale = 'en-us'
title = 'Duality'
theme = "hugo-coder"
defaultContentLanguage = "en"

[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = ""

[markup.highlight]
style = "github-dark"

[build]
  [build.postcss]
    # uses postcss.config.js automatically

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Duality"
  description = "all about physics-informed quantitative research, signal processing, data science, algorithms, and machine learning."
  info = "Physics-informed research on financial market structure."
  avatarURL = "images/duality_logo_v1.png"
  keywords = "physics-informed finance, quantitative research"
  dateFormat = "January 2, 2006"
  since = 2026
  enableTwemoji = true
  customCSS = ["site.css"]
  customJS = ["js/site.js"]

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # GTM container ID for analytics and tags (for example: GTM-ABC1234).
  [params.googleTagManager]
  id = "GTM-KH34MMJ3"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params.csp]
  childsrc = ["'self'"]
  fontsrc = [
    "'self'",
    "https://fonts.gstatic.com",
    "https://cdn.jsdelivr.net/"
  ]
  formaction = ["'self'"]
  framesrc = [
    "'self'",
    "https://www.googletagmanager.com"
  ]
  imgsrc = [
    "'self'",
    "https://www.google-analytics.com"
  ]
  objectsrc = ["'none'"]
  stylesrc = [
    "'self'",
    "'unsafe-inline'",
    "https://fonts.googleapis.com/",
    "https://cdn.jsdelivr.net/"
  ]
  scriptsrc = [
    "'self'",
    "'unsafe-inline'",
    "https://cdn.jsdelivr.net/",
    "https://www.google-analytics.com",
    "https://www.googletagmanager.com",
    "https://www.clarity.ms"
  ]
  # connect-src directive – defines valid targets for XMLHttpRequest (AJAX), WebSockets or EventSource
  connectsrc = [
    "'self'",
    "https://www.google-analytics.com",
    "https://region1.google-analytics.com",
    "https://stats.g.doubleclick.net",
    "https://*.clarity.ms"
  ]

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "Videos"
weight = 2
url = "videos/"

[[languages.en.menu.main]]
name = "Papers"
weight = 3
url = "papers/"

[[languages.en.menu.main]]
name = "Products"
weight = 4
url = "products/"